require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'

target 'EMovies' do

  platform :ios, '12.0'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-childprocess', :path => '../node_modules/react-native-childprocess'

  target 'EMoviesTests' do
    inherit! :complete
    # Pods for testing
  end

  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'EMovies-tvOS' do

  platform :tvos, '12.0'

  config = use_native_modules!

  # Hermes not yet available on tvOS
  use_react_native!(:path => config["reactNativePath"])

  target 'EMovies-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end
end

post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    end
  end
end
